### ISSUE TITLE
Home page: How can I help?

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#10]
At the bottom of the home page, the How can I help? Should be simply:

"To help with the Saivite Bible project, contact Acharya Arumuganathaswami at ar@hindu.org.
<img width="967" alt="screen shot 2018-10-07 at 3 41 01 pm" src="https://user-images.githubusercontent.com/33885813/46589635-a7b5d300-ca47-11e8-89e2-4bfaaea9c79b.png">
"

**Comment by Arumugaswami** [comment]
Not sure if you've worked on this, or if we are not understanding this the same way. We do not want "your name" "email" etc. Kapaa HI etc. should  not be there, contact@hindu.org should not be there, only the sentence I gave above, "To help with the Saivite Bible project, contact Acharya Arumuganathaswami at ar@hindu.org."

**Comment by subhakanta1979** [comment]
All Set Now, Please let me know
