### ISSUE TITLE
Lord Ganesha letters

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#20]
<img width="589" alt="screen shot 2018-10-07 at 4 15 02 pm" src="https://user-images.githubusercontent.com/33885813/46590056-34629000-ca4c-11e8-94c6-ae70cf3549c0.png">

There should be no "hamburger" menu on the left, all three letters should be on the same page.

**Comment by subhakanta1979** [comment]
Seems to be a Non Issue, All three Letters are rendered on the same page, The Left sidebar just shows three chapters menu wise from the Book "Letters From Lord Ganesha Include@", when we click on individual chapters it goes to another page with that specific chapter only, user can still use the left side-bar to go to the other letters/chapters, Requesting Acharyaji to re-evaluate this issue as this is as per the functionality.
