### ISSUE TITLE
Scripture introductions on home page

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#21]
<img width="835" alt="screen shot 2018-10-07 at 4 17 23 pm" src="https://user-images.githubusercontent.com/33885813/46590108-90c5af80-ca4c-11e8-8926-4dceada9da39.png">

Not seeing we need this listing of Vedas, Upanishads, etc., on the home page, as they only take you to the introduction, and nowhere else. This section can be deleted.

**Comment by subhakanta1979** [comment]
@Arumugaswami This issue is fixed, kindly validate and let me know.

**Comment by Arumugaswami** [comment]
I'm talking about the listing of Vedas, Upanishad, etc. across the purple bar in the screen shot above. I don't see what we need this as it only takes one to the introductions. 
![screen shot 2018-11-10 at 9 33 31 am](https://user-images.githubusercontent.com/33885813/48305278-d5b98780-e4cb-11e8-80b2-dcd598edff50.png)

**Comment by subhakanta1979** [comment]
As discussed with Acharyaji we are going to #1 Move The Intro above the "Intro to Individual Categories" as mentioned in the Screenshot below and "we'll have the links to the scriptures from the individual intro pages" from these linked pages.

![image](https://user-images.githubusercontent.com/43493826/48317112-399a9800-e613-11e8-9f87-3b10f21a6418.png)
