### ISSUE TITLE
Home page text

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#22]
<img width="835" alt="screen shot 2018-10-07 at 4 19 20 pm" src="https://user-images.githubusercontent.com/33885813/46590145-d08c9700-ca4c-11e8-8486-4b39d7f9bd49.png">

Above "Holy Bible of the Saivite Hindu Religion" in equal size type should read "Introduction"

Then "Main introduction" before "all my devotees..." can be deleted.

**Comment by subhakanta1979** [comment]
@Arumugaswami  This issue is fixed, kindly validate and let me know.
