### ISSUE TITLE
Tirumurai Authors

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#28]
For Tirumurai only, we need to list the author, such as Sambandar. This needs to be song by song, as in later Tirumurai there are multiple authors per book.

**Comment by Arumugaswami** [comment]
For each Tirumurai, the author should be entered in the "author" field, so it is only a matter of displaying the author to the public reader. If no author is entered, then we will have to fill that in later in the editing/review process.

**Comment by subhakanta1979** [comment]
I will get back to You on this, on the complexities involved , Adding Author even if Only in the Tirumurai Reading Interface.

**Comment by Arumugaswami** [comment]
Yes, having the author in the reading interface would suffice.
