### ISSUE TITLE
Grant Subhakanta Access

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#3]
Andre, I hope you can put this on the top of your list tomorrow (ahead of virtual tour)

I tried to give Subhakanta access to just one directory using Webmin.  I will send the log in details on Slack. 

1) I created a user : "subhakanta"
2) set his home directory to /home/himalayan/public_html/saivite-bible
3) added him to the group "himalayan"

I also a generic user on the MySql data base, that user can on see "saivite_bible" dbase in PHPMyAdmin.

-----
Well the PHPMyAdmin word. (he can only see on database)
but SFTP has issue. You can log in as "subhakanta" and you are can only see the inside of this directory "/home/himalayan/public_html/saivite-bible"  but two things happen

1) He doesn't have permissions to read and write 
2) He is also getting a time out from the server after three minutes. 

I suspect there is conflict between give a user a home directory that is also is public_html. But can't find setting related to this in Webmin.

**Comment by Arumugaswami** [comment]
done
