### ISSUE TITLE
TOC (Top Panel) should be in Synch with That of the Home Page

### ISSUE THREAD

**Issue by subhakanta1979** [Himalayan-Academy/Saivite-Bible#34]
Assigning to Myself, Please refer to the screenshot for more details.

![image](https://user-images.githubusercontent.com/43493826/47780062-9eefae80-dd20-11e8-971d-cedd174f7890.png)

**Comment by subhakanta1979** [comment]
@Arumugaswami  Namaste Acharyaji, Top Panel Hamburger Menu Items in the TOC is fixed, in synch with those of the Menu Items in the Home Page UI. The Hamburger Menu Items just disappear if You just click off it.

**Comment by Arumugaswami** [comment]
yet to be implement, relates to #29

**Comment by subhakanta1979** [comment]
@Arumugaswami Please close this Ticket, there is a ticket 29 for the same. This is not an Issue but an enhancement which requires a change in the data model again.
