### ISSUE TITLE
Clarify use of Bible approved/not approved, approved for public buttons

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#36]
"approve" Not understanding the wording on the right side. For example the first one says "Bible(approve)." I click it, and it updates to say "Bible(Not Approve)". If I click the second box, "approve for public", it changes to not approved. This is confusing. I don't think both boxes need to be clickable, that's part of the problem. The top one could say "click to toggle approved/not approved". The second box could then simply state "approved for public" or "not approved for public" but not in itself be clickable. Part of the confusion is for the bottom box which now says "approve for public" 
you mean "approved for public" which is the state of the verse, not an action which "approve" implies. We need to discuss this.

**Comment by subhakanta1979** [comment]
Noted, This was given above & beyound for searching all verses & chapters at one place, as discussed this section would be more clear to the user and would be part of our enhancement.
