### ISSUE TITLE
Upanishad flyout menu 

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#37]
In home page table of contents, Upanishad flyout menu should list all 14 Upanishads we have extracted from. 
Brhadaranyaka
Chandogya
Taittiriya
Isa
Kena
Katha
Mundaka
Mandukya
Svetasvatara
Maitri
Subala
Paingala
Kaivalya
Vajrasucika

**Comment by subhakanta1979** [comment]
We decided not to expand the Upanishads as there are so many, this involves a data model change and will it look nice to have all those 12-13 subcategories in the Sub Menu.
