### ISSUE TITLE
Integrate New SMTP details in saivite bible app

### ISSUE THREAD

**Issue by subhakanta1979** [Himalayan-Academy/Saivite-Bible#5]
We have to integrate new Microsoft Enterprise account “saivite-bible@hindu.org” in Saivite Bible App. I will touchbase with Swamiji for SMTP details of the Himalayan Server, this is needed for Email Alerts, Password change, inquiries , commentaries etc.

**Comment by Arumugaswami** [comment]
We have decided not to use the email server for round trip communications with people who would be either editors or reviewers. We also don't want to allow the general public to allow comments. This is over engineering for what may be at the most 20 possible participants who are engaged with the material. For this reason, I'm quite happy to give out the passwords for 20 individuals which will save us a large part of email administration of the server when it is not necessary. We would like to proceed in this manner. 

- [ ] On the contact page, indicate that a user may request review status (I would give the text for this later, you can put in anything for now). We're not seeing a need to give outsiders editing status.

- [ ] Then the external user can email me and I will give them a password by entering it myself into the reviewer user list ACL. 

- [ ] So you will need to provide a place for me to enter their email and password and then I will inform them that they have access.

**Comment by Arumugaswami** [comment]
@subhakanta1979 if you have questions we can talk about it on Skype.

**Comment by subhakanta1979** [comment]
> We have decided not to use the email server for round trip communications with people who would be either editors or reviewers. We also don't want to allow the general public to allow comments. This is over engineering for what may be at the most 20 possible participants who are engaged with the material. For this reason, I'm quite happy to give out the passwords for 20 individuals which will save us a large part of email administration of the server when it is not necessary. We would like to proceed in this manner.
> 
> * [ ]  On the contact page, indicate that a user may request review status (I would give the text for this later, you can put in anything for now). We're not seeing a need to give outsiders editing status.
> * [ ]  Then the external user can email me and I will give them a password by entering it myself into the reviewer user list ACL.
> * [ ]  So you will need to provide a place for me to enter their email and password and then I will inform them that they have access.

Acknowledged. I will get back to You on this.
Best Regards,
Subhakant

**Comment by Arumugaswami** [comment]
Decided not to have email registration on the server.
