### ISSUE TITLE
Vedas sections

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#6]
1. Separate according to Veda into Rig, Sama, Yajur, Atharva.

2. Put Rig first

3. Submenu needs to take you to one of the four vedas and not all at once

4. Missing titles at one point in the listing.

**Comment by subhakanta1979** [comment]
Acknowledged, Looking into it.

**Comment by subhakanta1979** [comment]
Veda Sorting Issues has been taken care of, please let me know (refer to the screenshot), will proceed with other issues in Vedas

**Comment by subhakanta1979** [comment]
Sure Acharyaji , Noted.

**Comment by Arumugaswami** [comment]
done
