### ISSUE TITLE
Delete "Login Forgot Password"

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#62]
Estimate time fix: 1 hour

If you to go a public to [Saivite Bible](https://www.himalayanacademy.com/saivite-bible)

click on [Login](https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view)

Either
a) nothing happens OR
b) you get this: 404 Page Not Found
<img width="665" alt="screen shot 2019-02-19 at 5 28 48 pm" src="https://user-images.githubusercontent.com/33885813/53064612-8987c700-346c-11e9-953b-7527ae97cf7d.png"t

**Comment by Brahmanathaswami** [comment]
This appears like a bug. On the other hand if you just did not code that part of the admin applications we think it should take an hour to fix this.

**Comment by subhakanta1979** [comment]
Namaste Swamiji, Acharyaji,
The correct URL is as shown below :- 
https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view

the url should have the admin after saivite-bible in order for it to work. Please retry and let me know if You still face any issues.

**Comment by Arumugaswami** [comment]
If you’re asking about my experience, I can no longer log in as “admin” or “AR-admin” which I used to be able to do, but I can log in as “AR-admin2” or “BR-admin”

Acharya Arumuganathaswami
Managing Editor

On 3/24/19, 10:00 AM, "subhakanta1979" <notifications@github.com<mailto:notifications@github.com>> wrote:


Namaste Swamiji, Acharyaji,
The correct URL is as shown below :-
https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view

the url should have the admin after saivite-bible in order for it to work. Please retry and let me know if You still face any issues.

**Comment by subhakanta1979** [comment]
@Arumugaswami  Let me quickly fix your login issue

**Comment by Brahmanathaswami** [comment]
I still get a 404 after entering my email....

**Comment by subhakanta1979** [comment]
@Arumugaswami  i am able to login using AR-Admin, anyways i have reseted your passowrd to abcd1234, please change your password upon login.  the link below

https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view

**Comment by subhakanta1979** [comment]
@Brahmanathaswami  Your user id is BR-admin, i am not sure of your password. are you using the below link to log in ?

https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view

**Comment by Arumugaswami** [comment]
OK, that worked.

Acharya Arumuganathaswami
Managing Editor

On 3/24/19, 10:18 AM, "subhakanta1979" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Arumugaswami<https://github.com/Arumugaswami> i am able to login using AR-Admin, anyways i have reseted your passowrd to abcd1234, please change your password upon login. the link below

https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/login_view

**Comment by Brahmanathaswami** [comment]
Maybe it just a UI problem! It says "Type your email"?

![2019-03-24_10-56-23](https://user-images.githubusercontent.com/3675722/54885729-81cc9100-4e23-11e9-971c-36c42529d059.png)

**Comment by Brahmanathaswami** [comment]
The URL is 👍 
https://www.himalayanacademy.com/saivite-bible/admin/index.php/user/lostpassword

Seems we can side track to "Login"

**Comment by Brahmanathaswami** [comment]
This feature was deprecated a long time ago, but we did not removed the button?Link from pages. Please delete it:  "Forget Password" on the log-in page.

**Comment by subhakanta1979** [comment]
Acknowledged.  I will trying using a work-around to to get the forget password work with the google SMTP else I will remove it.
Best Regards,
Subhakant

**Comment by subhakanta1979** [comment]
By the way forgot password is FIXED, you did not give your SMTP details but
i fixed it with Google's SMTP...you should be able to get a new password on
Your Google as soon as You key in Your mail id . I did not take more than
30 mins...hope it clarifies.

**Comment by Brahmanathaswami** [comment]
done
