### ISSUE TITLE
Time Out Error Happens on the DB Server while running a Procedure

### ISSUE THREAD

**Issue by subhakanta1979** [Himalayan-Academy/Saivite-Bible#7]
I am getting the attached error while executing a procedure, we are calling this procedure in the Admin Panel UI to reset the staging . We need to raise a support ticket to address this issue, this could be due to the memory / time out defined in the server settings.
I have attached both the screenshots 1-from the UI 2-another from PHPMYADMIN
CALL P_RESET_ALL_VERSES_INCLUDING_HISTORY ('Y'); 

![image](https://user-images.githubusercontent.com/43493826/46483914-5d99db00-c816-11e8-8614-695ccc72d09c.png)

![image](https://user-images.githubusercontent.com/43493826/46483825-2d523c80-c816-11e8-818a-fc17098dc2a6.png)

**Comment by Brahmanathaswami** [comment]
![2018-10-05_09-05-29](https://user-images.githubusercontent.com/3675722/46555157-2a8b3200-c87e-11e8-8517-1a623d252339.png)

**Comment by Brahmanathaswami** [comment]
Should these be changed?

**Comment by subhakanta1979** [comment]
> Should these be changed?

Namaste Swamiji, I believe php.ini default params should be as it is unless the system admin alters them to bring performance improvement, most likely it could be due to the db param settings (mysql -e "show processlist") , for e.g. net_write_timeout is an important db param along with wait_timeout and interactive_timeout are  the time of inactivity before the connection is dropped.

**Comment by Brahmanathaswami** [comment]
@soapdog I don't know if you know enough about mySQL to figure this out. We can't find anything that would produce there error he it talking about.

**Comment by subhakanta1979** [comment]
![image](https://user-images.githubusercontent.com/43493826/46906021-392ab680-cf1a-11e8-8b4e-46ad6de8f8ba.png)
![image](https://user-images.githubusercontent.com/43493826/46906474-b4dc3180-cf21-11e8-86e6-573aacaeeab8.png)
Subh says - The issue still persists, Screenshots from the Application and PHPMyADMIN are given for reference, It's due to DB system variables/parameters, We need to raise a ticket to the SysAdmin/DBA or I need 4-6 hours to troubleshoot it with the help of a DBA from my team but since I don't have the necessary access I need to share my insights with Swamiji to take it forward to the Concerned team. To put things into perspective, we are only dealing with 10K records (Verse records) to process from staging to the t_Verse table, should not be an issue. I might change the cursor approach written in the DB Procedure if it works. Requesting Acharyaji to reopen the ticket.

**Comment by Arumugaswami** [comment]
Will discuss with Brahmanathaswami this morning

**Comment by Arumugaswami** [comment]
When logging manual time on Upwork, is there a provision for saying what work was being done hour by hour?

**Comment by Arumugaswami** [comment]
See my message in upwork

**Comment by Arumugaswami** [comment]
Brahmanathaswami putting in a request to the service provider to sort this out.

**Comment by Brahmanathaswami** [comment]
@subhakanta1979 

We are seeing these errors in php-errors.log

[04-Oct-[04-Oct-2018 08:31:22 America/Los_Angeles] PHP Warning:  Module 'json' already loaded in Unknown on line 0
[08-Oct-2018 14:01:38 America/Los_Angeles] PHP Warning:  Module 'json' already loaded in Unknown on line 0
[09-Oct-2018 08:24:51 America/Los_Angeles] PHP Warning:  Module 'json' already loaded in Unknown on line 0
[14-Oct-2018 10:38:56 America/Los_Angeles] PHP Warning:  Module 'json' already loaded in Unknown on line 0

Confirm: these correspond to times you tried your trigger.

**Comment by Brahmanathaswami** [comment]
@subhakanta1979 
Please try you trigger again

NOTES:

for some reason, this one "wiki.hindu.org"  has a php ini file had these to lines enabled

extension=mysql.so
extension=json.so

But these extensions are automatically loaded from the /mods-available  on ini. e.g.

root@shiv:/etc/php5/mods-available# ls
curl.ini  curl.ini.ucf-old  gd.ini  json.ini  json.ini~  mysqli.ini  mysql.ini  opcache.ini  pdo.ini  pdo_mysql.ini  readline.ini
root@shiv:/etc/php5/mods-available# cat json.ini
; configuration for php json module
priority=20
extension=json.so
root@shiv:/etc/php

so I commented the duplicates extension loading them on:

 /home/wikihindorg/etc/php.ini  

line ~640-641
; extension=mysql.so
; extension=json.so

let hope that works

**Comment by subhakanta1979** [comment]
@Arumugaswami @Brahmanathaswami  Thanks Swamiji and Acharyaji, after the PHP.ini changes the database procedures and triggers seem to be running fine and I no longer see issues in the "Reprocess Staging" Module. Kindly update the status of this Issue to "Closed"

Best Regards,
Subhakant

**Comment by Brahmanathaswami** [comment]
@subhakanta1979: if it worked, please comment "fixed" and close this ticket.

**Comment by subhakanta1979** [comment]
@Arumugaswami @Brahmanathaswami  Finally I was able to Pinpoint the issue, the below SQL Query which Fetches just 9126 records (Verses) from the DB is running into issues on the Server. Yes that's right a mere SELECT statement which fetches 9126 records/verses from the Db is running into Issue on Himalayan Server and 9126 rows are not huge by any standard, as shown in the screenshot below the same query fetched all the rows from the DB in 23 seconds on my Local Machine. This is clearly a DB Issue and the DBA needs to allocate more memory and execution time to the Database on the Server, Happy to discuss it over a call. This will create issues going forward when the volume of record increases.

**SQL Query**
SELECT c.id verse_chapter_id,
	b.Contents,
	b.Verse_No Verse_No,
	b.Verse,
	a.incl_excl_flag approved_for_bible,
	'Staging_2_Verse ETL_Program' last_modified_by,
	current_timestamp modification_date,
	c.chapter_id,
	b.excel_content_id,
	a.Doc_Id lkp_doc_collection_id, 
	b.id stg_chapter_text_id,
	b.file_name 	stg_file_name,
	'ETL- Excel to MySQL' stg_created_by,
	b.creation_time stg_creation_time,
	b.verse_comments,
	b.chapter_no,
	b.Verse_Starting_No,
	b.Verse_Ending_No,
	b.Number_Of_Verses,
    b.section_no
	FROM t_docs_collection a inner join t_stg_doc_chapters_text b on ltrim(rtrim(a.doc_name)) = ltrim(rtrim(b.file_name))
	inner join t_chapter c on c.stg_file_name = b.file_name
	where c.excel_content_id = b.excel_content_id 	
	and c.chapter_no = b.chapter_no and ifnull(b.section_no,0) = 
    ifnull(c.section_no,0) order by a.incl_excl_flag,c.stg_file_name, c.chapter_no asc;	

**Screenshot (from my Local Machine V/S The Himalayan Server**
![image](https://user-images.githubusercontent.com/43493826/47080245-1dc6f080-d225-11e8-951b-ad657363a368.png)

**Comment by subhakanta1979** [comment]
@Brahmanathaswami @Arumugaswami  Problem Solved, I will close the ticket tonight. I have changed the Procedure Logic to do a batch Processing by diving the data into smaller chunks , I am no longer getting error message on PHPMYADMIN while running the below two Procedures 
CALL P_RESET_ALL_CHAPTERS_INCLUDING_HISTORY ('Y');
CALL P_RESET_ALL_VERSES_INCLUDING_HISTORY ('Y'); 
and on the UI (Reprocess Page) I am getting a success message as shown in the screenshot below, (i will do a small change on the UI PHP code). 
On a separate note Swamiji can still raise a ticket to the DBA to look into MySQL Config as running a query which fetches mere 9126 rows runs into issues on the Himalayan Server (Please refer to my earlier comment). 

![image](https://user-images.githubusercontent.com/43493826/47098453-e1a98500-d250-11e8-93a9-d46a26b50b17.png)

**Comment by subhakanta1979** [comment]
As discussed This issue is Fixed with the work-around on the Procedure side, hence i am closing it.

Best Regards,,
Subh
