### ISSUE TITLE
Please Give Us a List of Deprecated Tables in the Database

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#73]
Estimate Time To Fix: 1 hour

Please give us a list (Don't Drop Them! for Now) of the table which you feel are not used at all by the Frameworkd

**Comment by subhakanta1979** [comment]
Namaste Acharyaji, Swamiji,
Please find the list of tables and their descriptions, keep column tells us whether to keep them or delete them. 
[Saivite_Bible_Table_Dtls_03242019_V1.xlsx](https://github.com/Himalayan-Academy/Saivite-Bible/files/3000780/Saivite_Bible_Table_Dtls_03242019_V1.xlsx)

**Comment by Brahmanathaswami** [comment]
The excel spread sheet is very clean. Thank you.
