### ISSUE TITLE
Datebase-CSS-Controller Mapping

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#75]
[ ] https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/admin_addwithouteditor

1. please list the table.column for each of the fields. 
2. List the Label and the textarea # for each field: e.g
               Document Description; textarea id="scripture_text"

 [ ] where is the CSS files that lays about Look and Feel of this page (color, initial size etc.)?

 [ ] After the use makes the selections in the drop down options. [Subject |Document | Chapter Name | Verse Name] I see you use .ajax calls for the data queries. Where are the controllers and mySQL querIes that respond to these .ajax calls.? (I just need get a grip on how you are using Code Igniter.)
 
 var url ="https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/getdocuments";
     var url ="https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/getchapter";
 url: "https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/getdocumentinfo",
 var url ="https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/getverse";
$.ajax({
    url: "https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/getchapterinfo",

**Comment by subhakanta1979** [comment]
Acknowledged.I will provide You the details shortly.

Best Regards,
Subhakant

**Comment by Brahmanathaswami** [comment]
Any progress?

**Comment by subhakanta1979** [comment]
Sure Swamiji, I am back in my place now, I will keep You posted with the updates in a day or two.

Best Regards,
Subhakant

**Comment by subhakanta1979** [comment]
Namaste Swamiji, Acharyaji, Pfa, The Mapping Doc for Your reference, Apology for the delay.

Best Regards,
Subhakant
[Datebase-CSS-Controller Mapping.docx](https://github.com/Himalayan-Academy/Saivite-Bible/files/3104098/Datebase-CSS-Controller.Mapping.docx)

**Comment by Brahmanathaswami** [comment]
Fantastic!  We are involved into editorial July issue, so delay was not a problem. I will look around,. will get back to you in about two weeks with a good "spec" and what to do...

**Comment by subhakanta1979** [comment]
Thank You. Om Shanti.
