### ISSUE TITLE
Redo UI to Saiva Admin Page According to Zeplin

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#76]
See 

zpl://screen?sid=5d02a04359c9931608990a11&pid=5d029fafd6587e15d89e5ae0

Rework the UI layout according to new specs on Zeplin.  We are not re-wiring the back end to the fields, all current AJAX stays the same. with one exception, the comments box (see separate issue)

https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/admin_addwithouteditor

**Comment by Brahmanathaswami** [comment]
We did add one field in the new layout: 
![2019-06-21_10-17-47](https://user-images.githubusercontent.com/3675722/59949097-d4f7b500-940d-11e9-8b66-3eb1bb3c06ae.png)

**Comment by subhakanta1979** [comment]
Noted. WIP (Work in Progress). https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/admin_addwithouteditor_new1

**Comment by subhakanta1979** [comment]
We will do this once all other above mentioned issues are addressed and closed.

**Comment by Arumugaswami** [comment]
OK

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of,  Fixed.

**Comment by subhakanta1979** [comment]
Subh Says - We will do this once all other above mentioned issues are addressed and closed on GITHUB.
