### ISSUE TITLE
Change to "Comment by Reviewers" to be an iFrame include

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#77]
see: https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/admin_addwithouteditor

 see the Zeplin: new layout

At the top left-hand, second field down:

label: Comments by Reviewer 

 [ ] On the new admin interface,  bring in iframe that has the comments just on this verse. 
 [ ] It is basically a duplicate of the comments table  view 

https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/comments

filtered by the actual verse number. 

 [ ] On the right of those comments, there should be a delete button, we do not want to keep revisions Delete them from the comments table. 
  [ ] Put a cautionary prompt: 
                 "Are you sure you want to delete this comment" 
                              Cancel | Yes

**Comment by Brahmanathaswami** [comment]
On the left hand second field down, it says verse comments by reviewers. It does not show them. 

We don't understand if your "view all reviewer comments" button was intended to invoke all of the comments for the whole bible, which it does now. If you meant this to be a user interface strategy instead of implementing our iframe idea (which was not necessarily the best way to go), we think that is good, but it should only show the comments for this particular verse.

**Comment by subhakanta1979** [comment]
Noted, we will work on this new functionality and touchbase with You on Slack for any issues.

**Comment by subhakanta1979** [comment]
Looking into it, will update you soon on this.

**Comment by Arumugaswami** [comment]
We should include this in our next conversation. If you do the iframe as a popup above the interface to show us more comments, which is fine, we will have to deprecate the field on the interface and change the layout a little bit.
