### ISSUE TITLE
Delete Button on Comments Table (only admin can see this)

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#78]
Both in the iFrame and on the comment table

https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/comments

Next to each comment there needs to be a delete button for admin only.

[ ] Put a cautionary prompt:
"Are you sure you want to delete this comment"
Cancel | Yes

**Comment by subhakanta1979** [comment]
Sure Noted. We will implement this functionality as the iframe level and in the comments panel.

**Comment by subhakanta1979** [comment]
This is Fixed. Please note how the delete functionality is handled now, Only the admins can delete the comments. The reviewers cannot delete their own comments and before deleting it asks for a confirmation.

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of,  Fixed.
