### ISSUE TITLE
Next and Previous Buttons Don't Works

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#79]
see: https://www.himalayanacademy.com/saivite-bible/admin/index.php/saivite/admin_addwithouteditor

previous verse and next verse do no work.

**Comment by subhakanta1979** [comment]
It's been taken care of. We will revalidate it on the new Server.

**Comment by subhakanta1979** [comment]
It’s working fine now, Fixed.

**Comment by Arumugaswami** [comment]
Still not on our server

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of,  Fixed.
