### ISSUE TITLE
Verse Bhasyar (ancient or modern) Is Saved to Current Chapter Level

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#80]
If you add a note under label "Verse Bhasya" 

[we think the view is tied to t_verse.commentary, but we could be wrong] 

When we "Save and Submit" It should be entered into the current verse table. But instead, it is into entered the entire chapter (we think)

Symptom: You can see the this when going to another verse—the same data appears.

**Comment by subhakanta1979** [comment]
Yes You are right as there’s only one commentary field. I will add a new field called Chapter_Commentary to the DB and change the mapping of it at the chapter level in the chapter section.

**Comment by subhakanta1979** [comment]
Looking into it.

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of,  Fixed. 
![image](https://user-images.githubusercontent.com/43493826/66172283-edac7380-e668-11e9-941d-2510f1077f4f.png)
