### ISSUE TITLE
UI Labels Missing for the Top Two Fields

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#81]
Sorry, this did not come through on Zeplin, we don't understand why some problem with design in Adobe UX and updating the cloud....anyway...

Top two fields in the verse area need labels
a) Top left:  "Verse in English" 
b) Top right: "Verse: Editor's Production Notes"

**Comment by subhakanta1979** [comment]
Can You please add this two fields in the Zeplyn , or a simple mock up in paint , where we want to add these two fields

**Comment by subhakanta1979** [comment]
Do we want Labels or Just the watermark on the Text Boxes are good enough for the reviewers to understand these fields.
Top two fields in the verse area need labels
a) Top left: "Verse in English"
b) Top right: "Verse: Editor's Production Notes"

**Comment by Arumugaswami** [comment]
?watermark? should be like the rest of the interface, pls use labels.

**Comment by subhakanta1979** [comment]
Ok Noted.

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of  Fixed.
