### ISSUE TITLE
Chapter Level Metadata Not Save to Database

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#82]
All of the fields in the black "chapter level editing and notes": When we add a new note to any of those fields, click "Save and Publish", go to a different chapter and come back, the chapter notes have not been saved, or perhaps they are saved to the dbase but are not picked up by the view.

**Comment by subhakanta1979** [comment]
This was taken care of, we will validate again once the New Server is up and running.

**Comment by subhakanta1979** [comment]
This was taken care of,  Fixed.

**Comment by Arumugaswami** [comment]
We think you've updated your local host/xxamp, but not published to our server.

**Comment by subhakanta1979** [comment]
![image](https://user-images.githubusercontent.com/43493826/65267482-b56a4880-db32-11e9-9077-f96436154157.png)
Please refer to the screenshot , we have separate commentary field at Verse Level, Chapter Level and Document Level. Similarly i have added another new field chapter_translators_notes at the chapter level. I tested it again , we are able to save data at the chapter level. Please note that we are now changing the mappings for the new fields we have added at the chapter level. i will keep you posted on this.
![image](https://user-images.githubusercontent.com/43493826/65268174-3fff7780-db34-11e9-9624-0b4601115b49.png)

**Comment by subhakanta1979** [comment]
Subh Says This was taken care of,  Fixed.
