### ISSUE TITLE
Metadata Panel at Bottom is Non-Functional

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#84]
The area in interface related to the book metadata: Number of Verses, Translator, Entered by, etc. are non functional. Even in the old interface we can make entries in the fields by they are not saved to the dbase.

![2019-08-06_12-39-32](https://user-images.githubusercontent.com/3675722/62582186-42896480-b847-11e9-9a65-665bb7b0165f.png)

**Comment by subhakanta1979** [comment]
![image](https://user-images.githubusercontent.com/43493826/63643128-e13b0f80-c6e7-11e9-8746-3ee03a45a448.png)
@Brahmanathaswami  Please refer to the attached image, we understand the NUMBER stand for "Number of Verses" in that Chapter. This would be static and non-updateable , rest others can be made functional and editable.

**Comment by subhakanta1979** [comment]
This is working fine. Please refer to the Open Question section in the document I am going to share it via email. 2-	What exactly is a Traditiona field in the chapter section below , is it the Bhasya / Commentary field , we have captured from the Google docs ?

**Comment by subhakanta1979** [comment]
Subh Says - As discussed, this is working and Fixed
