### ISSUE TITLE
"Link to:" and  "Audio" and the "Yes" and "No" (Approval Radio Buttons) Not functional

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#85]
This area on the UI in non-functional. Should be save to the t_verse table,. We need labels next the radio bottons also

![2019-08-06_12-45-46](https://user-images.githubusercontent.com/3675722/62582441-23d79d80-b848-11e9-9a4b-708936e26cec.png)

**Comment by subhakanta1979** [comment]
Sure Swamiji, Noted.

**Comment by subhakanta1979** [comment]
It's a small change as we have fields in the T_Verse table, we are changing the HTML

**Comment by subhakanta1979** [comment]
This has been taken care of , we will do some more validations on the new server and update You.

**Comment by subhakanta1979** [comment]
Made them Functional and It’s working now, We will add the Labels , this is a small cosmetic change

Tested It’s working fine. 

Quick Question for Swamiji: When we say Approved for Public = N , we are successfully hiding those Verses on the Public UI , similarly Should we also hide the verse where Approved for Bible = N, At the moment we are displaying everything in the “Admin Panel” regardless of Approved for Bible = N/Y for a certain Verse.

**Comment by Arumugaswami** [comment]
It is correct that the admin panel should show all verses in the scripture, both approved and not approved. One would know from the yes/no section their include/exclude status.

Acharya Arumuganathaswami
Managing Editor

On 9/17/19, 12:44 PM, "subhakanta1979" <notifications@github.com<mailto:notifications@github.com>> wrote:


Made them Functional and It’s working now, We will add the Labels , this is a small cosmetic change

Tested It’s working fine.

Quick Question for Swamiji: When we say Approved for Public = N , we are successfully hiding those Verses on the Public UI , similarly Should we also hide the verse where Approved for Bible = N, At the moment we are displaying everything in the “Admin Panel” regardless of Approved for Bible = N/Y for a certain Verse.

**Comment by Brahmanathaswami** [comment]
Hyou need to go to git hub and make the comment there…


Svasti Astu, Be Well!
Brahmanathaswami

Get the SivaSiva app, it's free:
https://www.himalayanacademy.com/apps/sivasiva

It is correct that the admin panel should show all verses in the scripture, both approved and not approved. One would know from the yes/no section their include/exclude status.

Acharya Arumuganathaswami
Managing Editor

On 9/17/19, 12:44 PM, "subhakanta1979" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com%3e>> wrote:


Made them Functional and It’s working now, We will add the Labels , this is a small cosmetic change

Tested It’s working fine.

Quick Question for Swamiji: When we say Approved for Public = N , we are successfully hiding those Verses on the Public UI , similarly Should we also hide the verse where Approved for Bible = N, At the moment we are displaying everything in the “Admin Panel” regardless of Approved for Bible = N/Y for a certain Verse.

**Comment by Arumugaswami** [comment]
The boolean "approved for bible" means that it is definitely included in the print edition or can be use in the public interface of an app or other situations. 
The boolean "approved for public" is really a review process by a wider group of editors, eg "the public" and not admin as such. We really should have called it "under evaluation." Following your convention we did not change the table name but added a comment in the column definition.
![Screen Shot 2019-09-17 at 3 54 22 PM](https://user-images.githubusercontent.com/33885813/65101254-17288800-d964-11e9-9a44-3d117b3711c1.png)
This likewise applies to the chapter level. 
![Screen Shot 2019-09-17 at 3 59 55 PM](https://user-images.githubusercontent.com/33885813/65101595-43440900-d964-11e9-9cad-8b18df55b58f.png)

**Comment by Arumugaswami** [comment]
It would be appreciated if the background colors matched the design.

**Comment by subhakanta1979** [comment]
Sure Acharyaji, As discussed with Swamiji We can set up a call with our designer and we can fix the design related issues. Our custom CSS files are in this path 

Frontend CSS:
 https://www.himalayanacademy.com/saivite-bible/assets/fronttheme/style.css
 Admin CSS:
https://www.himalayanacademy.com/saivite-bible/admin/assets/css/developer.css

I am attaching the screenshot of admin panel bootstrap CSS path.

![image](https://user-images.githubusercontent.com/43493826/65264851-2444a300-db2d-11e9-84e8-a193df7caf54.png)

**Comment by subhakanta1979** [comment]
Subh Says:- 
As discussed , Tested It’s working fine.
