### ISSUE TITLE
extra intro paragraph

### ISSUE THREAD

**Issue by Arumugaswami** [Himalayan-Academy/Saivite-Bible#9]
This paragraph: "We have two classes: 1. An introduction to one of the five collections: Vedas, Agamas, Ancient Saints, Tirumurai, Modern Saints 2. An introduction to individual works--presently this is just a few, but will likely be expanded upon in the future. The mapping for class one will go to a different table--the one for the five collections. This is different than the table for individual works." 

Should not be in the introduction on the home page. This was a note to you. 
<img width="802" alt="screen shot 2018-10-07 at 3 39 32 pm" src="https://user-images.githubusercontent.com/33885813/46589596-51e12b00-ca47-11e8-891a-3103a1b8a2d0.png">

**Comment by Arumugaswami** [comment]
I fixed this myself, but we still have two "introductions" on this page and should remove the top one, which is programmed in. The second one I could edit.
<img width="697" alt="screen shot 2018-10-24 at 4 11 24 pm" src="https://user-images.githubusercontent.com/33885813/47471788-9c80d800-d7a7-11e8-9d1f-3c546631c096.png">

**Comment by subhakanta1979** [comment]
@Acharyaji I have fixed it, the extra "introduction" has been removed.
